### ISSUE TITLE
3D and 2D augmentation functions.

### ISSUE THREAD

**Issue by Joearrowsmith** [Knee-Deep-in-MRI/DeepSegmentation#40]

**Comment by arahosu** [comment]
2D Augmentation is now implemented in augmentation.py [https://github.com/Knee-Deep-in-MRI/DeepSegmentation/blob/Merge_Pipeline/Segmentation/utils/augmentation.py](url)

**Comment by Joearrowsmith** [comment]
3D augmentation complete.
