### ISSUE TITLE
Distributed training for 3d models

### ISSUE THREAD

**Issue by Joearrowsmith** [Knee-Deep-in-MRI/DeepSegmentation#47]

**Comment by Joearrowsmith** [comment]
https://www.tensorflow.org/guide/distributed_training#using_tfdistributestrategy_with_keras

**Comment by Joearrowsmith** [comment]
Currently unable to add distributed training, needs further exploration.

**Comment by arahosu** [comment]
Distributed training now works with 3D data. Closing the issue
