### ISSUE TITLE
Not using features in parse function for image dimensions.

### ISSUE THREAD

**Issue by Joearrowsmith** [Knee-Deep-in-MRI/DeepSegmentation#58]
https://github.com/Knee-Deep-in-MRI/DeepSegmentation/blob/4d2164ffb522671c450a6dece94c5656dfb77293/Segmentation/utils/data_loader.py#L184

Added the correct implementation for 3d on line 185. Parse_fn_2d might need to be corrected.

**Comment by arahosu** [comment]
Thanks for pointing that out. Will close the issue since it's been addressed.
