### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mylepalliprithvi** [Knee-Deep-in-MRI/DeepSegmentation#77]
Hi, can I get the MRI Images dataset. I need it for my college project work.

**Comment by arahosu** [comment]
Hi Mylepalli, I no longer have access to the IWOAI challenge dataset. If you need it, please contact [Akshay](https://profiles.stanford.edu/akshay-chaudhari) or [Neal](https://www.boisestate.edu/coen-ece/directory/bangerter/). Hope that helps.

**Comment by mylepalliprithvi** [comment]
Hi Joonsu,
Thank you for your response. Will try contacting them.

Regards,
Prithvi Mylepalli
